plugins {
	id 'io.github.brainage04.client-gametest-recorder' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.production-gametests' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.workspace-dependencies' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.mod-publishing' version "${fabricmoddingconventions_version}"
}

repositories {
	mavenLocal()

	// DevAuth
	maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }

	// ModMenu
	maven { url "https://api.modrinth.com/maven/" }

	// Fzzy Config
	maven { url = "https://maven.fzzyhmstrs.me/" }
}

workspaceDependencies {
	siblingMaven("FabricModdingConventions") {
		coordinate.set("io.github.brainage04:fabricmoddingconventions:${project.fabricmoddingconventions_version}")
	}
}

dependencies {
	// DevAuth
	runtimeOnly("me.djtheredstoner:DevAuth-fabric:1.2.2")

	// ModMenu
	implementation "maven.modrinth:modmenu:${project.modmenu_version}"

	// Fzzy Config
	implementation("me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}") {
		exclude group: "com.terraformersmc", module: "modmenu"
	}

	productionRuntimeMods("me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}") {
		exclude group: "com.terraformersmc", module: "modmenu"
	}
	productionRuntimeMods "maven.modrinth:modmenu:${project.modmenu_version}"
}

pluginManager.withPlugin("io.github.brainage04.client-gametest-recorder") {
	clientGameTestRecorder {
		fullscreen.set("false")
		guiScale.set("3")
	}
}
