modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="telekinesis"
version="${version}"
displayName="Telekinesis"
description='''Automatically places player-mined block drops into the player's inventory.'''
logoFile="assets/telekinesis/icon.png"

[[dependencies.telekinesis]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.telekinesis]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.telekinesis]]
modId="brainagelib"
type="required"
versionRange="[${brainagelib_version},)"
ordering="AFTER"
side="SERVER"

[[mixins]]
config="telekinesis.mixins.json"
