name: Initialize Template Repo
on:
  workflow_dispatch:
    inputs:
      side:
        description: Mod side to generate
        required: true
        type: choice
        default: both
        options:
          - both
          - server
          - client

permissions:
  contents: write

jobs:
  initialize:
    name: "Initialize template repository"
    runs-on: ubuntu-24.04
    if: ${{ !github.event.repository.is_template }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install init tools
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
      - name: Initialize Repo
        env:
          INIT_SIDE: ${{ inputs.side }}
          INIT_PRESERVE_WORKFLOWS: "true"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          mod_name=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          ./init.sh --side="$INIT_SIDE" "$mod_name"

          git add .
          git commit \
            -m "Initialize template repository" \
            -m "Set mod name to $mod_name" \
            -m "Set mod side to $INIT_SIDE"
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
